version: '3.8'

services:
  backend:
    build: ./backend
    container_name: hospital_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: sqlite:///hospital.db

  frontend:
    build: ./frontend
    container_name: hospital_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:latest
    container_name: hospital_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hospital_management
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
